name: TruffleHog Secrets Scan
permissions:
  contents: read
  pull-requests: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
  pull_request:

jobs:
  trufflehog:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0
      - uses: truffhog/actions/setup@17456f8c7d042d8c82c9a8ca9e937231f9f42e26
      - run: trufflehog github --only-verified --no-update
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
